apiVersion: v1
kind: Service
metadata:
  name: stress-api
spec:
  ports:
  - port: 3000
    nodePort: 30000
    protocol: TCP
    targetPort: 3000
  selector:
    run: stress-api
  type: NodePort
status:
  loadBalancer: {}
