# from https://raw.githubusercontent.com/ufcg-lsd/provisionamento/master/kubernetes/config/tlsconfig.yaml
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
serverTLSBootstrap: true
