---
- name: Init cluster with kubeadm
  ansible.builtin.shell: |
    kubeadm init --pod-network-cidr=192.168.1.0/24

- name: Create .kube directory
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    mode: '0755'

- name: Copy admin.conf from /etc/kubernetes to .kube
  ansible.builtin.copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Print join command to worker nodes
  ansible.builtin.shell: kubeadm token create --print-join-command
  register: join_command_result

- name: Setting join command as a fact to worker nodes can use the command
  ansible.builtin.set_fact:
    join_command: "{{ join_command_result.stdout }}"
    cacheable: true

- name: Config pod network plugin with Weave
  become: false
  ansible.builtin.shell: |
    kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml

- name: Taint control-plane node
  become: false
  ansible.builtin.shell: |
    kubectl taint nodes --all node-role.kubernetes.io/control-plane-