---
- name: Init cluster with kubeadm
  ansible.builtin.shell: |
    kubeadm init --pod-network-cidr=192.168.1.0/24

- name: Create .kube directory
  ansible.builtin.file:
    path: /home/{{ ansible_user }}/.kube
    state: directory
    mode: '0755'

- name: Copy admin.conf from /etc/kubernetes to .kube
  ansible.builtin.copy:
    remote_src: true
    src: /etc/kubernetes/admin.conf
    dest: /home/{{ ansible_user }}/.kube/config
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Print join command to worker nodes
  ansible.builtin.shell: kubeadm token create --print-join-command | tee /tmp/join_command.sh

- name: Fetching /tmp/join_command.sh to k8s-worker/files
  ansible.builtin.fetch:
    src: /tmp/join_command.sh
    dest: "{{ playbook_dir }}/roles/k8s-worker/files/"
    flat: true

- name: Config pod network plugin with Weave
  become: false
  ansible.builtin.shell: |
    kubectl apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml

- name: Taint control-plane node
  become: false
  ansible.builtin.shell: |
    kubectl taint nodes --all node-role.kubernetes.io/control-plane-