---
- name: Load overlay kernel module
  modprobe:
    name: overlay
    state: present

- name: Load br_netfilter kernel module
  modprobe:
    name: br_netfilter
    state: present

- name: Reload system modules
  ansible.builtin.shell: sysctl --system

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted