---
- name: Install K8S on cluster
  hosts: all
  become: true
  roles:
    - k8s

- name: Initialize cluster on control-plane
  hosts: control-plane
  become: true
  roles:
    - k8s-control-plane

- name: Worker nodes join control plane node
  hosts: workers
  become: true
  roles:
    - k8s-worker