- name: wget zabbix package
  ansible.builtin.shell: cd /tmp && wget https://repo.zabbix.com/zabbix/6.2/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.2-4%2Bubuntu22.04_all.deb

- name: Install zabbix apt repository
  ansible.builtin.apt:
    deb: /tmp/zabbix-release_6.2-4+ubuntu22.04_all.deb

- name: Install zabbix agent
  ansible.builtin.apt:
    update_cache: true
    pkg:
      - zabbix-agent

- name: Granting access to zabbix server
  ansible.builtin.shell: |
    sed -i "s/Server=127.0.0.1/Server=192.168.1.0\/24/" /etc/zabbix/zabbix_agentd.conf

- name: Enable and restart Zabbix agent
  ansible.builtin.systemd:
    name: zabbix-agent
    enabled: true
    state: restarted

