---
- name: Download and add GPG Key
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg

- name: Add K8S repository to /etc/apt/sources.list
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Update apt repository and install kubernetes and its dependencies
  ansible.builtin.apt:
    pkg:
      - kubectl=1.24.0-00
      - kubeadm=1.24.0-00
      - kubelet=1.24.0-00
      - containerd
      - apt-transport-https
      - ca-certificates
    update_cache: true

- name: Create /etc/containerd dir
  ansible.builtin.file:
    path: /etc/containerd
    state: directory
    mode: '0744'

- name: Set default config to containerd
  ansible.builtin.shell: |
    containerd config default > /etc/containerd/config.toml
  notify:
  - Restart containerd

- name: Config K8s modules
  ansible.builtin.template:
    src: k8s_modules.conf.j2
    dest: /etc/modules-load.d/k8s.conf
  notify:
  - Load overlay kernel module
  - Load br_netfilter kernel module

- name: Config network modules
  ansible.builtin.template:
    src: k8s_sysctl.conf.j2
    dest: /etc/sysctl.d/k8s.conf
  notify:
  - Reload system modules

- name: Turn off the swap
  ansible.builtin.shell: swapoff -a