---
- name: Download and add GPG Key
  ansible.builtin.get_url:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    dest: /usr/share/keyrings/kubernetes-archive-keyring.gpg

- name: Add K8S repository to /etc/apt/sources.list
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
    filename: kubernetes.list

- name: Install Docker
  become: false
  ansible.builtin.shell: |
    curl -fsSL https://get.docker.com | bash
    sudo usermod -aG docker ubuntu

- name: Update apt repository and install kubernetes and its dependencies
  ansible.builtin.apt:
    pkg:
      - kubectl=1.24.0-00
      - kubeadm=1.24.0-00
      - kubelet=1.24.0-00
      - apt-transport-https
      - ca-certificates
      - git
      - golang-go
    update_cache: true

- name: Config K8s modules
  ansible.builtin.template:
    src: k8s_modules.conf.j2
    dest: /etc/modules-load.d/k8s.conf
  notify:
  - Load overlay kernel module
  - Load br_netfilter kernel module

- name: Config network modules
  ansible.builtin.template:
    src: k8s_sysctl.conf.j2
    dest: /etc/sysctl.d/k8s.conf
  notify:
  - Reload system modules

- name: Turn off the swap
  ansible.builtin.shell: swapoff -a

- name: Install container runtime cri-dockerd
  ansible.builtin.shell: |
    git clone https://github.com/Mirantis/cri-dockerd.git && \
    cd cri-dockerd && \
    mkdir bin && \
    go build -o bin/cri-dockerd && \
    mkdir -p /usr/local/bin && \
    install -o root -g root -m 0755 bin/cri-dockerd /usr/local/bin/cri-dockerd && \
    cp -a packaging/systemd/* /etc/systemd/system && \
    sed -i -e "s,/usr/bin/cri-dockerd,/usr/local/bin/cri-dockerd," /etc/systemd/system/cri-docker.service && \
    systemctl daemon-reload && \
    systemctl enable --now cri-docker.service && \
    systemctl enable --now cri-docker.socket
